
name: 'saad_dashboard'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
  - "target"
  - "dbt_packages"


models:
  saad_dashboard:
   staging:
    +materialized: view
   intermediate:
    +materialized: view
    +schema: intermediate
   marts:
    +materialized: table
    dashboard:
      +schema: dashboard
    marketing:
      +schema: marketing

